# Generated by Django 5.1.4 on 2024-12-12 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base_user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cousine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets",
                        to="base_user.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("name_az", models.CharField(blank=True, max_length=250, null=True)),
                ("name_en", models.CharField(blank=True, max_length=250, null=True)),
                ("name_tr", models.CharField(blank=True, max_length=250, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=250, null=True)),
                ("name_ar", models.CharField(blank=True, max_length=250, null=True)),
                ("name_ko", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="mealImages"),
                ),
                ("price", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "number_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("vegan", models.BooleanField(default=False)),
                ("ingredient", models.TextField(blank=True, null=True)),
                ("ingredient_az", models.TextField(blank=True, null=True)),
                ("ingredient_en", models.TextField(blank=True, null=True)),
                ("ingredient_tr", models.TextField(blank=True, null=True)),
                ("ingredient_ru", models.TextField(blank=True, null=True)),
                ("ingredient_ar", models.TextField(blank=True, null=True)),
                ("ingredient_ko", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("is_halal", models.BooleanField(blank=True, default=False, null=True)),
                ("is_new", models.BooleanField(blank=True, default=False, null=True)),
                ("etp", models.CharField(blank=True, max_length=100, null=True)),
                ("calorie", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="meal_videos/"),
                ),
                ("priority", models.IntegerField(default=0)),
                ("iiko_id", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "cousine",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="meals", to="meals.cousine"
                    ),
                ),
                (
                    "created_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_user.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="base_user.client",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="meals.meal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_az", models.CharField(max_length=200, null=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_tr", models.CharField(max_length=200, null=True)),
                ("name_ru", models.CharField(max_length=200, null=True)),
                ("name_ar", models.CharField(max_length=200, null=True)),
                ("name_ko", models.CharField(max_length=200, null=True)),
                ("icon", models.ImageField(upload_to="CatImages")),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, null=True)),
                (
                    "created_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_user.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="MealImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="meal_images")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="meals.meal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=250, null=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="meals.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("size_az", models.CharField(blank=True, max_length=100, null=True)),
                ("size_en", models.CharField(blank=True, max_length=100, null=True)),
                ("size_tr", models.CharField(blank=True, max_length=100, null=True)),
                ("size_ru", models.CharField(blank=True, max_length=100, null=True)),
                ("size_ar", models.CharField(blank=True, max_length=100, null=True)),
                ("size_ko", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="meals.meal",
                    ),
                ),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meals.basket",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meals.meal"
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meals.mealsize",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="meals.basket",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="base_user.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_az", models.CharField(max_length=200, null=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_tr", models.CharField(max_length=200, null=True)),
                ("name_ru", models.CharField(max_length=200, null=True)),
                ("name_ar", models.CharField(max_length=200, null=True)),
                ("name_ko", models.CharField(max_length=200, null=True)),
                ("order", models.IntegerField(default=0)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sub_category_images"
                    ),
                ),
                (
                    "created_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_user.restaurant",
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meals.mealcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
            },
        ),
        migrations.AddField(
            model_name="mealcategory",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="meals.subcategory"),
        ),
        migrations.AddField(
            model_name="meal",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meals",
                to="meals.subcategory",
            ),
        ),
    ]
