version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: farid
      POSTGRES_DB: DemoQr
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data: