# Generated by Django 5.1.4 on 2024-12-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="UserFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("net", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("order_id", models.CharField(max_length=100)),
                ("refund_id", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "refund_transaction_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("card_name", models.CharField(blank=True, max_length=200, null=True)),
                ("card_mask", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "waiter_card_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "waiter_card_mask",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_successful", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.currency",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="base_user.waiter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantDiscounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="discounts")),
                ("is_active", models.BooleanField(default=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "created_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_user.restaurant",
                    ),
                ),
            ],
        ),
    ]
