# Generated by Django 5.1.4 on 2024-12-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iiko_id", models.CharField(max_length=100)),
                (
                    "name",
                    models.CharField(
                        choices=[("Cashback", "Cashback"), ("Discount", "Discount")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Coupons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="client_coupons/")),
                (
                    "number",
                    models.CharField(max_length=255, verbose_name="Number of Coupon"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base_user.client",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base_user.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iiko_id", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurants",
                    models.ManyToManyField(
                        blank=True, null=True, to="base_user.restaurant"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loyalty.programs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Category",
                "verbose_name_plural": "Loyalty Categories",
                "ordering": ("name",),
            },
        ),
    ]
