# Generated by Django 5.1.4 on 2024-12-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_az", models.CharField(blank=True, max_length=100, null=True)),
                ("name_en", models.CharField(blank=True, max_length=100, null=True)),
                ("name_tr", models.CharField(blank=True, max_length=100, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=100, null=True)),
                ("name_ar", models.CharField(blank=True, max_length=100, null=True)),
                ("name_ko", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="exhibit"),
                ),
                ("sound", models.FileField(blank=True, null=True, upload_to="exhibit")),
                (
                    "sound_az",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "sound_en",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "sound_tr",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "sound_ru",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "sound_ar",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "sound_ko",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                ("video", models.FileField(blank=True, null=True, upload_to="exhibit")),
                (
                    "video_az",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "video_en",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "video_tr",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "video_ru",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "video_ar",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                (
                    "video_ko",
                    models.FileField(blank=True, null=True, upload_to="exhibit"),
                ),
                ("text", models.TextField()),
                ("text_az", models.TextField(null=True)),
                ("text_en", models.TextField(null=True)),
                ("text_tr", models.TextField(null=True)),
                ("text_ru", models.TextField(null=True)),
                ("text_ar", models.TextField(null=True)),
                ("text_ko", models.TextField(null=True)),
                ("additional_text", models.TextField(blank=True, null=True)),
                ("additional_text_az", models.TextField(blank=True, null=True)),
                ("additional_text_en", models.TextField(blank=True, null=True)),
                ("additional_text_tr", models.TextField(blank=True, null=True)),
                ("additional_text_ru", models.TextField(blank=True, null=True)),
                ("additional_text_ar", models.TextField(blank=True, null=True)),
                ("additional_text_ko", models.TextField(blank=True, null=True)),
                (
                    "image_1",
                    models.ImageField(blank=True, null=True, upload_to="exhibit/"),
                ),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="exhibit/"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="exhibit/"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="exhibit/"),
                ),
                (
                    "image_5",
                    models.ImageField(blank=True, null=True, upload_to="exhibit/"),
                ),
                (
                    "museum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base_user.museum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exhibit",
                "verbose_name_plural": "Exhibits",
            },
        ),
    ]
